export const ROUTES = {
  HOME: '/',
  ENROLLMENT: `/enrollment`,
  CHECKOUT: '/checkout',
  CONTACT: '/contact-us',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/my-account/change-password',
  ACCOUNT: '/user/account/account-settings',
  ORDERS: '/user/account/orders',
  ACCOUNT_SETTING: '/user/account/account-settings',
  ADDRESS: '/user/account/address',
  PAYMENT: '/my-account/payment',
  HELP_CENTER: '/user/account/help-center',
  LEGAL_NOTICE: '/my-account/legal-notice',
  NOTIFICATION: '/user/account/notification',
  SHOPS: '/shops',
  LOGIN: '/signin',
  SIGN_UP: '/signup',
  SEARCH: '/search',
  PRODUCTS: '/products',
  BUNDLE: '/bundles',
  CATEGORY: '/category',
  ORDER: '/complete-order',
  WISHLIST: '/my-account/wishlist',
};
